# Generated by Django 4.2.1 on 2023-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drpapp', '0002_deadclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadclick',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
