# Generated by Django 4.2.1 on 2023-06-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drpapp', '0003_alter_deadclick_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadclick',
            name='class_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deadclick',
            name='element_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deadclick',
            name='tag_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deadclick',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='deadclick',
            name='x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deadclick',
            name='y',
            field=models.IntegerField(null=True),
        ),
    ]
